### PR TITLE
Add link to Swiss version

### PR DESCRIPTION
**Pull request by orangecms**
There cannot be enough of this. It will never end. 🇨🇭🧀

### CODE REVIEW

**Comment by devlocalhost** [comment]
Hey there. You should make a PR to include the swiss version to the original repo ([this one](https://github.com/bnjbvr/rouille) ), instead to a fork of the original repo. 

Check out: https://github.com/bnjbvr/rouille/pulls?q=is%3Apr+is%3Aclosed

**Comment by orangecms** [comment]
yea fair point, will do 🥳

**Comment by orangecms** [comment]
see https://github.com/bnjbvr/rouille/pull/53 :eyes: - feel free to close this and cherry-pick etc :)

**Comment by devlocalhost** [comment]
> see [bnjbvr#53](https://github.com/bnjbvr/rouille/pull/53) 👀 - feel free to close this and cherry-pick etc :)

Will do once your PR is merged, so I can fetch the other commits too

**Pull request closed without merging**
